-- MySQL Script generated by MySQL Workbench
-- Wed May 16 15:36:06 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_guiwb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_guiwb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_guiwb` DEFAULT CHARACTER SET utf8 ;
USE `db_guiwb` ;

-- -----------------------------------------------------
-- Table `db_guiwb`.`tb_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_guiwb`.`tb_users` (
  `iduser` INT(11) NOT NULL AUTO_INCREMENT,
  `desname` VARCHAR(64) NOT NULL,
  `desemail` VARCHAR(128) NOT NULL,
  `deslogin` VARCHAR(64) NOT NULL,
  `despassword` VARCHAR(256) NOT NULL,
  `nrphone` BIGINT(20) NULL DEFAULT NULL,
  `inadmin` TINYINT(4) NOT NULL DEFAULT '0',
  `dtregister` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `deslogin_UNIQUE` (`deslogin` ASC),
  UNIQUE INDEX `desemail_UNIQUE` (`desemail` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_guiwb`.`tb_userspasswordsrecoveries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_guiwb`.`tb_userspasswordsrecoveries` (
  `idrecovery` INT(11) NOT NULL AUTO_INCREMENT,
  `iduser` INT(11) NOT NULL,
  `desip` VARCHAR(45) NOT NULL,
  `dtrecovery` DATETIME NULL DEFAULT NULL,
  `dtregister` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idrecovery`),
  INDEX `fk_userspasswordsrecoveries_users_idx` (`iduser` ASC),
  CONSTRAINT `fk_userspasswordsrecoveries_users`
    FOREIGN KEY (`iduser`)
    REFERENCES `db_guiwb`.`tb_users` (`iduser`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `db_guiwb` ;

-- -----------------------------------------------------
-- procedure sp_users_delete
-- -----------------------------------------------------

DELIMITER $$
USE `db_guiwb`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_users_delete`(
piduser INT(11)
)
BEGIN

	DELETE FROM tb_userspasswordsrecoveries WHERE iduser = piduser;
    DELETE FROM tb_users WHERE id_user = piduser;

END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_users_save
-- -----------------------------------------------------

DELIMITER $$
USE `db_guiwb`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_users_save`(
piduser INT(11),
pdesname VARCHAR(64),
pdesemail VARCHAR(128),
pdeslogin VARCHAR(64),
pdespassword VARCHAR(256),
pnrphone BIGINT(20),
pinadmin TINYINT(4)
)
BEGIN

	IF piduser > 0 THEN
    
		##IF iduser IS GREATER THAN ZERO, YOU MUST UPDATE AN EXISTING RECORD.
		UPDATE
			tb_users
		SET
			desname = pdesname,
            desemail = pdesemail,
            deslogin = pdeslogin,
            despassword = pdespassword,
            nrphone = pnrphone,
            inadmin = pinadmin
		WHERE
			iduser = piduser;
            
    ELSE
		##IF NOT, CREATE A NEW RECORD.
		INSERT INTO tb_users
        (desname, desemail, deslogin, despassword, nrphone, inadmin)
		VALUES
        (pdesname, pdesemail, pdeslogin, pdespassword, pnrphone, pinadmin);
        
    END IF;

END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_userspasswordsrecoveries_create
-- -----------------------------------------------------

DELIMITER $$
USE `db_guiwb`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_userspasswordsrecoveries_create`(
piduser INT,
pdesip VARCHAR(45)
)
BEGIN
	
	INSERT INTO tb_userspasswordsrecoveries (iduser, desip) VALUES(piduser, pdesip);
    SELECT * FROM tb_userspasswordsrecoveries WHERE idrecovery = LAST_INSERT_ID();
    
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
